var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');


var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var cors = require("cors");
var app = express();
var login = require('./routes/login');
var stateview = require('./routes/stateview');
var district = require('./routes/district');
var State_Delete = require('./routes/State_Delete');
var distrite_view = require('./routes/distrite_view');
var districte_Delete = require('./routes/districte_Delete');
var designations = require('./routes/designations');
var designations_view = require('./routes/designations_view');
var designations_del = require('./routes/designations_del');
var employeeins = require('./routes/employeeins');
var employee_view = require('./routes/employee_view');
var uploads = require('./routes/uploads');
var employeeview = require('./routes/employeeview');
var employee_delete = require('./routes/employee_delete');
var employee_edit = require('./routes/employee_edit');
var jobvacancy_reg = require('./routes/jobvacancy_reg');
var jobvacancy_view = require('./routes/jobvacancy_view');
var jobvacancy_del = require('./routes/jobvacancy_del');
var project = require('./routes/project');
var project_del = require('./routes/project_del');
var project_view = require('./routes/project_view');
var project_work = require('./routes/project_work');
var Work_add = require('./routes/Work_add');
var work_view = require('./routes/work_view');
var work_del = require('./routes/work_del');
var careersignup = require('./routes/careersignup');
var leave_view = require('./routes/leave_view');
var leave_del = require('./routes/leave_del');
var leave_update = require('./routes/leave_update');
var apply = require('./routes/apply');
var work_assign = require('./routes/work_assign');
var job_view = require('./routes/job_view');
var jobseeker_update = require('./routes/jobseeker_update');
var jobseeker_view = require('./routes/jobseeker_view');
var jobseeker_status = require('./routes/jobseeker_status');
var jobseeker_apply_view = require('./routes/jobseeker_apply_view');
var new_empinsert = require('./routes/new_empinsert');
var work_assign_view = require('./routes/work_assign_view');
var deleteworkassign = require('./routes/deleteworkassign');
var work_emp_view = require('./routes/work_emp_view');
var progress = require('./routes/progress');
var progress_view = require('./routes/progress_view');
var leave_req = require('./routes/leave_req');
var emp_leave_view = require('./routes/emp_leave_view');
var Update_leave_req = require('./routes/Update_leave_req');
var leave_emp_view = require('./routes/leave_emp_view');
var message= require('./routes/message');
var message_view= require('./routes/message_view');
var Update_message= require('./routes/Update_message');
var message_emp_view= require('./routes/message_emp_view');
var search= require('./routes/search');
var jobseeker_edit = require('./routes/jobseeker_edit');
var offerletter = require('./routes/offerletter');
var piechart = require('./routes/piechart');
var leavehistory = require('./routes/leavehistory');
var barchart = require('./routes/barchart');
var report = require('./routes/report');
var reportexcel = require('./routes/reportexcel');

app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
global.__basedir = path.resolve(path.dirname('')); 

app.use(cors());
app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/login', login);
app.use('/stateview', stateview);
app.use('/district', district);
app.use('/State_Delete', State_Delete);
app.use('/distrite_view', distrite_view);
app.use('/districte_Delete', districte_Delete);
app.use('/designations', designations);
app.use('/designations_view', designations_view);
app.use('/designations_del', designations_del);
app.use('/employeeins', employeeins);
app.use('/uploads', uploads);
app.use('/employee_view', employee_view);
app.use('/employeeview', employeeview);
app.use('/employee_delete', employee_delete);
app.use('/employee_edit', employee_edit);
app.use('/jobvacancy_reg', jobvacancy_reg);
app.use('/jobvacancy_view', jobvacancy_view);
app.use('/jobvacancy_del', jobvacancy_del);
app.use('/project', project);
app.use('/project_del', project_del);
app.use('/project_view', project_view);
app.use('/project_work', project_work);
app.use('/Work_add', Work_add);
app.use('/work_view', work_view);
app.use('/work_del', work_del);
app.use('/careersignup', careersignup);
app.use('/leave_view', leave_view);
app.use('/leave_del', leave_del);
app.use('/leave_update', leave_update);
app.use('/apply', apply);
app.use('/work_assign', work_assign);
app.use('/job_view', job_view);
app.use('/jobseeker_update', jobseeker_update);
app.use('/jobseeker_view', jobseeker_view);
app.use('/jobseeker_status', jobseeker_status);
app.use('/jobseeker_apply_view', jobseeker_apply_view);
app.use('/new_empinsert', new_empinsert);
app.use('/work_assign_view', work_assign_view);
app.use('/deleteworkassign', deleteworkassign);
app.use('/work_emp_view', work_emp_view);
app.use('/progress', progress);
app.use('/progress_view', progress_view);
app.use('/leave_req', leave_req);
app.use('/emp_leave_view', emp_leave_view);
app.use('/Update_leave_req', Update_leave_req);
app.use('/leave_emp_view', leave_emp_view);
app.use('/message', message);
app.use('/message_view', message_view);
app.use('/Update_message', Update_message);
app.use('/message_emp_view', message_emp_view);
app.use('/search', search);
app.use('/jobseeker_edit', jobseeker_edit);
app.use('/offerletter', offerletter);
app.use('/piechart', piechart);
app.use('/leavehistory', leavehistory);
app.use('/barchart', barchart);
app.use('/report', report);
app.use('/reportexcel', reportexcel);
module.exports = app;
